# Generated by Django 5.1.5 on 2025-01-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationsetting_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='followed_actors',
            new_name='people',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='user_mail',
        ),
    ]
