# Generated by Django 5.1.5 on 2025-01-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
